spring:
  servlet:
    multipart:
      location: /nas/project/blog/blogTempFile

blog:
  file:
    path: /nas/project/blog
  front:
    path: ./front
  just:
    path: /home/linuxbrew/.linuxbrew/bin/just
  portfolio:
    path: /nas/project/blog/portfolio

origin:
  url: https://blog.devstat.com
