spring:
  application:
    name: blog

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #global?? ??
      open-in-view: false
    data:
      web:
        pageable:
          default-page-size: 20
          max-page-size: 2000

server:
  serverlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8903

logging:
  level:
    root: info

    # Hibernate SQL
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace

    # 트랜잭션
    org.springframework.transaction: debug

    # 웹
    org.springframework.web: debug
    org.springframework.boot.autoconfigure.web: debug

    # HikariCP
    com.zaxxer.hikari: debug

    # 내 애플리케이션 패키지
    devstat.blog: debug

jwtSecretKey: ENC(7GsY1475yK8bJJ55QAleJWu19r+sup9gwQBcOIo+6JNTGfU1znsr4hP6WjN3kYsB)