spring:
  servlet:
    multipart:
      location: /nas/project/blog/blogTempFile

blog:
  file:
    path: /nas/project/blog
  front:
    path: ./front
  just:
    path: /opt/homebrew/bin/just

origin:
  url: https://blog.devstat.com
