blog:
  file:
    path: /Users/ABCD/blogTempFile

origin:
  url: http://localhost:3000

init:
  user:
    alias: ENC(Q3j6aggVkiZ/oTty0xFg5Q==)
    name: ENC(gQ3xKbW+4R/2zjouy7xGJL+3Lo1I36Qy)
    password: ENC(83BIqOEgGK/btBWJ1m5GFS0qXXcUwlPM)