spring:
  application:
    name: blog

server:
  serverlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8903

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      # show_sql: true
      format_sql: true
      default_batch_fetch_size: 100 #global?? ??
    open-in-view: false
  data:
      web:
        pageable:
          default-page-size: 20
          max-page-size: 2000

logging:
  level:
    root: info # ?? ?? ?? ??
    # Hibernate SQL ??
    org.hibernate.SQL: debug # ???? ??
    org.hibernate.type.descriptor.sql: trace # ???? ???? ?

    # Spring ?? ?? ??
    org.springframework.web: debug
    org.springframework.boot.autoconfigure.web: debug

    # ??? ?? Exception ??
    devstat.blog: debug

jwtSecretKey: ENC(/dmaD89iAo2bFpDLHgX7pHe/AsTS/JpwW0QANm/Q7g3oL1a2303WlqGXwA0d2xlY)
