blog:
  file:
    path: /Users/ABCD/blogTempFile
  front:
    path: /Users/ABCD/Develop/Project/Blog/front
  just:
    path: /opt/homebrew/bin/just
  portfolio:
    path: /Users/ABCD/blogTempFile/portfolio

origin:
  url: http://localhost:3000

init:
  user:
    alias: ENC(dyh4J0F39S5VfOqNki3Buw==)
    name: ENC(iJyFHjwEy+YWp0P8W2pKUN+/RL23Suqk)
    password: ENC(bf/nuHy6xLDotvVKFyLA6YFTvegBHtxm)
