import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import request from 'sync-request';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// API 서버에서 데이터 동기적으로 가져오기
let docsInfo = [];
try {
    const res = request(
        'GET',
        process.env.API_SERVER + '/info/ABCD/docs'
    );
    docsInfo = JSON.parse(res.getBody('utf8'));
} catch (err) {
    console.error('❌ API 호출 실패:', err);
}

// 사이드바 구성
const sidebars: SidebarsConfig = {};

// API로부터 받은 정보 기반으로 사이드바 구성
if (Array.isArray(docsInfo) && docsInfo.length > 0) {
    docsInfo.forEach((doc) => {
        // 예: doc.sidebarId = "OS", doc.targetFolder = "FrameWork"
        sidebars[doc.sidebarId] = [
            { type: 'autogenerated', dirName: doc.targetFolder },
        ];
    });
}

export default sidebars;

