// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// import { $axios } from './src/api';
//
// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
//
// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation
//
//  The sidebars can be generated from the filesystem, or explicitly defined here.
//
//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//     // By default, Docusaurus generates a sidebar from the docs folder structure
//     // Blog: [{ type: 'autogenerated', dirName: '.' }],
//     // OS: [{ type: 'autogenerated', dirName: 'FrameWork' }],
//
//     // But you can create a sidebar manually
//     /*
//     tutorialSidebar: [
//       'intro',
//       'hello',
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//      */
// };
//
// export default sidebars;
//
// sidebars.ts

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import request from 'sync-request';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// API 서버에서 데이터 동기적으로 가져오기
let docsInfo = [];
try {
    const res = request(
        'GET',
        process.env.API_SERVER + '/info/ABCD/docs'
    );
    docsInfo = JSON.parse(res.getBody('utf8'));
} catch (err) {
    console.error('❌ API 호출 실패:', err);
}

// 사이드바 구성
const sidebars: SidebarsConfig = {};

// API로부터 받은 정보 기반으로 사이드바 구성
if (Array.isArray(docsInfo) && docsInfo.length > 0) {
    docsInfo.forEach((doc) => {
        // 예: doc.sidebarId = "OS", doc.targetFolder = "FrameWork"
        sidebars[doc.sidebarId] = [
            { type: 'autogenerated', dirName: doc.targetFolder },
        ];
    });
}

export default sidebars;

